In [1]:
import numpy as np

In [2]:
array1 = np.array([11,2,3])

In [3]:
array1

array([11,  2,  3])

In [43]:
array = np.array([[[[1,2],[2,3]],[[1,2],[2,3]],[[1,2],[2,3]]]])

In [177]:
new = np.random.randint(-10,10,size=(3,3,3))
new

array([[[ -8,   8,  -9],
        [-10,   1,  -6],
        [  6,   2,   3]],

       [[ -8,  -8,   3],
        [ -4,   2, -10],
        [  9,   3,   1]],

       [[ -4,   3,   1],
        [  0, -10,  -3],
        [  2,   9,  -6]]])

In [182]:
new3=new<5
new3

array([[[ True, False,  True],
        [ True,  True,  True],
        [False,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [False,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]]])

In [183]:
new[new%2==0]

array([ -8,   8, -10,  -6,   6,   2,  -8,  -8,  -4,   2, -10,  -4,   0,
       -10,   2,  -6])

In [316]:
arr = np.random.randint(3,size=(6))
arr

array([0, 0, 2, 0, 1, 2])

In [317]:
arr.sort()
print(arr)

[0 0 0 1 2 2]


In [318]:
np.unique(arr)

array([0, 1, 2])

In [341]:
a1 = np.random.randint(6,size=(2,2))
a1

array([[2, 4],
       [4, 0]])

array([[4, 0],
       [0, 3]])

In [343]:
np.intersect1d(a1,a2)

array([0, 4])

In [344]:
np.union1d(a1,a2)

array([0, 2, 3, 4])

In [345]:
np.setdiff1d(a1,a2)

array([2])

In [347]:
np.setdiff1d(a2,a1)

array([3])

In [349]:
np.in1d(a1,a2)

array([False,  True,  True,  True])

In [350]:
a1+a2

array([[6, 4],
       [4, 3]])

In [15]:
a1 = np.random.randint(10,size=(2,3,4))
a1

array([[[3, 0, 2, 2],
        [2, 3, 7, 7],
        [1, 9, 6, 6]],

       [[4, 6, 9, 0],
        [2, 0, 1, 1],
        [9, 9, 4, 6]]])

In [16]:
a1.shape

(2, 3, 4)

In [17]:
a1.sum(axis=0)

array([[ 7,  6, 11,  2],
       [ 4,  3,  8,  8],
       [10, 18, 10, 12]])

In [18]:
a1.sum(axis=1)

array([[ 6, 12, 15, 15],
       [15, 15, 14,  7]])

In [19]:
a1.sum(axis=2)

array([[ 7, 19, 22],
       [19,  4, 28]])